### ISSUE TITLE
License

### ISSUE THREAD

**Issue by basicer** [msinilo/zmachine#1]
Would you consider adding an opensouce license?

I'd like to use this project as an example in a project featuring TinyGo, WASI, and some other technologies.

**Comment by msinilo** [comment]
Sure. Quite frankly, I do not know much about licenses, which one is the most permissive right now?

**Comment by basicer** [comment]
MIT is my favorite for most permissible.

**Comment by msinilo** [comment]
Done.

**Comment by basicer** [comment]
Thanks!
